name = "DMRG"
uuid = "f33d63ad-f497-4648-8588-263974a41f95"
authors = ["Sergio Sánchez Ramírez <sergio.sanchez.ramirez@bsc.es> and contributors"]
version = "0.1.0"

[deps]
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
julia = "1"
